name: swagger docs
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  generate:
    strategy:
      matrix:
        go-version: [1.18.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout repository
        uses: actions/checkout@v3

      # Get values for cache paths to be used in later steps
      - name: Cache path
        id: cache-paths
        run: |
          echo "::set-output name=go-cache::$(go env GOCACHE)"
          echo "::set-output name=go-mod-cache::$(go env GOMODCACHE)"

      - name: Cache go modules
        uses: actions/cache@v3
        with:
          path: |
            ${{ steps.cache-paths.outputs.go-cache }}
            ${{ steps.cache-paths.outputs.go-mod-cache }}
          key: go-swag-${{ matrix.os }}-${{ matrix.go-version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: go-swag-${{ matrix.os }}-${{ matrix.go-version }}

      # CLI tool is needed to run "swag" commands
      - name: Install swag
        run: go install github.com/swaggo/swag/cmd/swag@latest

      # Check swag fmt can flawlessly format comments without any error
      - name: Format swag
        run: swag fmt

      # Check swag can generate docs without any error
      - name: Generate swag
        run: swag init
